version: "3.8"

services:
  mongo:
    container_name: docker-node-app-mongo
    image: mongo
    restart: unless-stopped
    networks:
      - docker-node-app-network
    volumes:
      - mongo-data:/data/db

  redis:
    container_name: docker-node-app-redis
    image: redis:alpine
    restart: unless-stopped
    networks:
      - docker-node-app-network
    volumes:
      - redis-data:/data
      - redis-dump:/var/lib/redis

  server:
    container_name: docker-node-app-server
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - REDIS_HOST=redis://docker-node-app-redis
      - MONGO_HOST=mongodb://mongo:27017/docker-node-app-mongo
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongo
      - redis
    networks:
      - docker-node-app-network

networks:
  docker-node-app-network:
    driver: bridge

volumes:
  mongo-data:
  redis-data:
  redis-dump:
