version: "3.8"

services:
  mongo:
    container_name: node-app-mongo
    image: mongo
    restart: unless-stopped
    networks:
      - node-app-network
    volumes:
      - mongo-data:/data/db
    ports:
      - ${MONGO_PORT}:27017

  redis:
    container_name: node-app-redis
    image: redis:alpine
    restart: unless-stopped
    networks:
      - node-app-network
    volumes:
      - redis-data:/data
      - redis-dump:/var/lib/redis
    ports:
      - ${REDIS_PORT}:6379

  server:
    container_name: node-app-server
    build: .
    env_file: .env
    environment:
      - MONGO_HOST=mongodb://mongo:27017/node-app-mongo
      - REDIS_HOST=redis://node-app-redis
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    networks:
      - node-app-network
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

networks:
  node-app-network:
    driver: bridge

volumes:
  mongo-data:
  redis-data:
  redis-dump:
