version: "3"

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - SERVER_PORT=${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
